// ----------------------------------------------------------------------

export const fullName = [
  'Jayvion Simon',
  'Lucian Obrien',
  'Deja Brady',
  'Harrison Stein',
  'Reece Chung',
  'Lainey Davidson',
  'Cristopher Cardenas',
  'Melanie Noble',
  'Chase Day',
  'Shawn Manning',
  'Soren Durham',
  'Cortez Herring',
  'Brycen Jimenez',
  'Giana Brandt',
  'Aspen Schmitt',
  'Colten Aguilar',
  'Angelique Morse',
  'Selina Boyer',
  'Lawson Bass',
  'Ariana Lang',
  'Amiah Pruitt',
  'Harold Mcgrath',
  'Esperanza Mcintyre',
  'Mireya Conner',
  'Jamie Kline',
  'Laney Vazquez',
  'Tiffany May',
  'Dexter Shepherd',
  'Jaqueline Spencer',
  'Londyn Jarvis',
  'Yesenia Butler',
  'Jayvon Hull',
  'Izayah Pope',
  'Ayana Hunter',
  'Isabell Bender',
  'Desiree Schmidt',
  'Aidan Stout',
  'Jace Bush',
  'Janiya Williamson',
  'Hudson Alvarez'
];
export const status = [
  'Active',
  'Inactive',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Inactive',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Active',
  'Inactive'
];

export const firstName = [
  'Mossie',
  'David',
  'Ebba',
  'Chester',
  'Eula',
  'Jaren',
  'Boyd',
  'Brady',
  'Aida',
  'Anastasia',
  'Gregoria',
  'Julianne',
  'Ila',
  'Elyssa',
  'Lucio',
  'Lewis',
  'Jacinthe',
  'Molly',
  'Brown',
  'Fritz',
  'Keon',
  'Ella',
  'Ken',
  'Whitney',
  'Monte',
  'Rose',
  'Shana',
  'Devon',
  'Jaleel',
  'Laury',
  'Brooks',
  'Bruce',
  'Avery',
  'Esperanza',
  'Helene',
  'Heloise',
  'Elinor',
  'Adeline',
  'Haley',
  'Anabelle'
];

export const lastName = [
  'Carroll',
  'Simonis',
  'Yost',
  'Hand',
  'Emmerich',
  'Wilderman',
  'Howell',
  'Sporer',
  'Boehm',
  'Morar',
  'Koch',
  'Reynolds',
  'Padberg',
  'Watsica',
  'Upton',
  'Yundt',
  'Pfeffer',
  'Parker',
  'Zulauf',
  'Treutel',
  'McDermott',
  'McDermott',
  'Cruickshank',
  'Parisian',
  'Auer',
  'Turner',
  'Dooley',
  'Wiegand',
  'Abbott',
  'Wisoky',
  'Fahey',
  'Satterfield',
  'Bahringer',
  'Schulist',
  'Durgan',
  'Carroll',
  'Jones',
  'Leffler',
  'Gutkowski',
  'Homenick'
];

export const eventsTitle = [
  'Introduction of Gaura Ecosystem',
  'X-Pic Project Presentation',
  'Gaura Ecosystem Dubai Event',
  'GAURA Ecosystem India Meetup',
  'Indonasia Community Meetup',
  'X-Pic Launching Moments',
  'NFT Making Process'
];
export const eventsLink = [
  'https://www.youtube.com/watch?v=2Ixv7F5hRyc',
  'https://www.youtube.com/watch?v=ZysEarObrR0',
  'https://www.youtube.com/watch?v=uB4SC6jG7mw',
  'https://www.youtube.com/watch?v=HOeoE-wGoUc',
  'https://www.youtube.com/watch?v=d473_7IqJSY',
  'https://www.youtube.com/watch?v=YxaG1tv2yOw',
  'https://www.youtube.com/watch?v=d473_7IqJSY',
  'https://www.youtube.com/watch?v=iuYM7nGys0E'
];
export const eventsIMG = [
  '/thumbnail/maxresdefault.jpg',
  '/thumbnail/xpic-presentetion.jpg',
  '/thumbnail/dubai-event.jpg',
  '/thumbnail/india-event.jpg',
  '/thumbnail/indonasia-event.jpg',
  '/thumbnail/x-pic-lauching.jpg',
  '/thumbnail/efil-tower-design.jpg'
];
